services:
  gateway:
    build:
      context: ./gateway-agent
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: production
      PORT: 3001
      RESEARCH_AGENT_URL: http://research:4111
      WRITING_AGENT_URL: http://writing:4112
      ANALYSIS_AGENT_URL: http://analysis:4113
    healthcheck:
      interval: 30s
      timeout: 5s
      retries: 3

  research:
    build:
      context: ./research-agent
    environment:
      NODE_ENV: production
      PORT: 4111
    healthcheck:
      interval: 30s
      timeout: 5s
      retries: 3

  writing:
    build:
      context: ./writing-agent
    environment:
      NODE_ENV: production
      PORT: 4112
    healthcheck:
      interval: 30s
      timeout: 5s
      retries: 3

  analysis:
    build:
      context: ./analysis-agent
    environment:
      NODE_ENV: production
      PORT: 4113
    healthcheck:
      interval: 30s
      timeout: 5s
      retries: 3
